services:
    go-api-srv:
        container_name: food_shuffle_api
        build:
            context: ./go-api-srv
            dockerfile: ./Dockerfile
        ports:
            - ${GO_PORT}:${GO_PORT}
        volumes:
            - ./go-api-srv/share:/root/share
        env_file:
            - .env
        working_dir: /root/share
        tty: true

    redis:
        container_name: food_shuffle_redis
        image: redis:7.4.1-bookworm
        ports:
            - ${REDIS_PORT}:6379
        environment:
            TZ: ${TZ:-Asia/Tokyo}

    mysql:
        container_name: food_shuffle_mysql
        build:
            context: ./mysql-srv
            dockerfile: ./Dockerfile
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        environment:
            TZ: ${TZ:-Asia/Tokyo}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./mysql-srv/data:/var/lib/mysql
        tty: true
